name: erik-cert
channels:
  - pytorch
  - anaconda
  - conda-forge
  - soumith
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cffi=1.12.1=py36h2e261b9_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=h746ee38_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=h6c8ec71_1
  - grpcio=1.27.2=py36hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=hf484d3e_1000
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py36_0
  - jpeg=9b=h024ee3a_2
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.0.0=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py36_0
  - keras-applications=1.0.6=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.0.3=py36h5429711_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - nltk=3.4.1=py36_0
  - notebook=6.0.3=py36_0
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1e=h7b6447c_0
  - pandas=0.24.2=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.6.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.3=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.6.1=py36he6710b0_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytorch=1.0.1=py3.6_cuda9.0.176_cudnn7.4.2_2
  - pytz=2019.2=py_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.1=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - scipy=1.2.1=py36h7c811a0_0
  - send2trash=1.5.0=py36_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - sqlite=3.26.0=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he68c306_0
  - tensorflow-base=1.12.0=gpu_py36h8e0ae2d_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - torchfile=0.1.0=py_0
  - torchvision=0.2.1=py_2
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.3=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - alabaster==0.7.12
    - allennlp==0.8.4
    - argcomplete==1.9.4
    - argh==0.26.2
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - awscli==1.16.194
    - babel==2.7.0
    - blis==0.2.4
    - boto3==1.9.184
    - botocore==1.12.184
    - bottle==0.12.9
    - chardet==3.0.4
    - click==7.0
    - codalab==0.5.13
    - colorama==0.3.9
    - conllu==0.11
    - cvxpy==1.0.25
    - cymem==2.0.2
    - cython==0.29.12
    - decorator==4.4.0
    - diffimg==0.2.3
    - dill==0.3.0
    - docker==3.7.0
    - docker-pycreds==0.4.0
    - docutils==0.14
    - dynet==2.1
    - ecos==2.0.7.post1
    - editdistance==0.5.3
    - flaky==3.6.0
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.5.1
    - fusepy==2.0.4
    - future==0.17.1
    - gevent==1.4.0
    - greenlet==0.4.15
    - idna==2.8
    - imagesize==1.1.0
    - importlib-metadata==0.18
    - itsdangerous==1.1.0
    - jinja2==2.10.1
    - jmespath==0.9.4
    - joblib==0.13.2
    - jsondiff==1.2.0
    - jsonnet==0.13.0
    - jsonpickle==1.2
    - jsonschema==3.0.1
    - marshmallow==2.15.1
    - marshmallow-jsonapi==0.15.1
    - more-itertools==7.1.0
    - multiprocess==0.70.8
    - murmurhash==1.0.2
    - networkx==2.3
    - numpydoc==0.9.1
    - osqp==0.5.0
    - overrides==1.9
    - packaging==19.0
    - parsimonious==0.8.1
    - pathtools==0.1.2
    - plac==0.9.6
    - pluggy==0.12.0
    - preshed==2.0.1
    - psutil==5.6.6
    - py==1.8.0
    - pyasn1==0.4.5
    - pygments==2.4.2
    - pymaxflow==1.2.12
    - pyrsistent==0.15.3
    - pytest==5.0.1
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.0.0
    - pyyaml==5.1
    - regex==2019.6.8
    - requests==2.22.0
    - responses==0.10.6
    - rsa==3.4.2
    - s3transfer==0.2.1
    - scikit-learn==0.21.2
    - scs==2.1.1-2
    - selenium==3.141.0
    - sentencepiece==0.1.82
    - six==1.11.0
    - snowballstemmer==1.9.0
    - spacy==2.1.4
    - sphinx==2.1.2
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - sqlalchemy==1.3.0
    - sqlparse==0.3.0
    - srsly==0.0.7
    - tensorboardx==1.8
    - thinc==7.0.4
    - unidecode==1.1.1
    - urllib3==1.25.3
    - wasabi==0.2.2
    - watchdog==0.8.3
    - wcwidth==0.1.7
    - websocket-client==0.57.0
    - werkzeug==0.15.4
    - word2number==1.1
    - zipp==0.5.2
prefix: /sailhome/erjones/.conda/envs/erik-cert

